In [1]:
import pickle

import numpy as np

In [2]:
with open('C:/Users/kenbun/PycharmProjects/ProtKenbunTalk/Excel_News/headline_list.pickle', mode='rb') as f:
    headline_list = pickle.load(f)

In [3]:
headline_list

[('こども大分新聞',
  '1932年',
  '10月',
  '2-y-2_01',
  'んぐみ\n| day\n三人組の隨一 ジ一堅い信念を貫いた。\nBEATION FLOR ANATUREHOU\n||||',
  array([ 2.85334135e-02, -1.92424072e-01,  4.56039086e-02, -1.21572739e-01,
          5.43569260e-02, -8.04633881e-02,  1.42244629e-01,  4.84711464e-02,
         -6.95362596e-02, -2.53570667e-01, -4.38268935e-02, -2.08972626e-01,
          1.47661157e-01,  3.18773596e-02,  1.22357806e-01, -1.81464867e-01,
         -5.14888508e-02, -1.59252781e-01, -6.51690907e-02, -1.59144810e-01,
          1.48869692e-01,  2.38188535e-01, -4.47835935e-01,  1.02226345e-01,
          1.60676936e-01,  3.15182216e-01,  1.23004975e-01,  8.79980767e-02,
         -1.12062171e-02, -1.33395967e-02,  4.06598071e-01, -6.86439675e-02,
          9.20450424e-02, -1.60790030e-01, -3.88190009e-02, -1.27351085e-01,
         -1.17866222e-01,  2.71082427e-01, -1.44796919e-01,  2.43953652e-02,
         -3.11696849e-01,  1.32733437e-01, -1.54891530e-01, -1.88269018e-01,
         -1.79980007e-01, -1.54783231e-

In [5]:
import pandas as pd

In [6]:
test_vector = headline_list[0][5]

In [7]:
test_vector

array([ 2.85334135e-02, -1.92424072e-01,  4.56039086e-02, -1.21572739e-01,
        5.43569260e-02, -8.04633881e-02,  1.42244629e-01,  4.84711464e-02,
       -6.95362596e-02, -2.53570667e-01, -4.38268935e-02, -2.08972626e-01,
        1.47661157e-01,  3.18773596e-02,  1.22357806e-01, -1.81464867e-01,
       -5.14888508e-02, -1.59252781e-01, -6.51690907e-02, -1.59144810e-01,
        1.48869692e-01,  2.38188535e-01, -4.47835935e-01,  1.02226345e-01,
        1.60676936e-01,  3.15182216e-01,  1.23004975e-01,  8.79980767e-02,
       -1.12062171e-02, -1.33395967e-02,  4.06598071e-01, -6.86439675e-02,
        9.20450424e-02, -1.60790030e-01, -3.88190009e-02, -1.27351085e-01,
       -1.17866222e-01,  2.71082427e-01, -1.44796919e-01,  2.43953652e-02,
       -3.11696849e-01,  1.32733437e-01, -1.54891530e-01, -1.88269018e-01,
       -1.79980007e-01, -1.54783231e-01,  1.77714914e-01, -6.40949660e-02,
        2.53398390e-01,  5.30334362e-02, -2.45716168e-01,  1.02266999e-02,
       -3.11027291e-02,  

In [8]:
type(test_vector)

numpy.ndarray

In [9]:
np.savetxt('test.csv', test_vector, delimiter=',')

In [10]:
read_test_vector = np.loadtxt('test.csv')

In [11]:
read_test_vector

array([ 2.85334135e-02, -1.92424072e-01,  4.56039086e-02, -1.21572739e-01,
        5.43569260e-02, -8.04633881e-02,  1.42244629e-01,  4.84711464e-02,
       -6.95362596e-02, -2.53570667e-01, -4.38268935e-02, -2.08972626e-01,
        1.47661157e-01,  3.18773596e-02,  1.22357806e-01, -1.81464867e-01,
       -5.14888508e-02, -1.59252781e-01, -6.51690907e-02, -1.59144810e-01,
        1.48869692e-01,  2.38188535e-01, -4.47835935e-01,  1.02226345e-01,
        1.60676936e-01,  3.15182216e-01,  1.23004975e-01,  8.79980767e-02,
       -1.12062171e-02, -1.33395967e-02,  4.06598071e-01, -6.86439675e-02,
        9.20450424e-02, -1.60790030e-01, -3.88190009e-02, -1.27351085e-01,
       -1.17866222e-01,  2.71082427e-01, -1.44796919e-01,  2.43953652e-02,
       -3.11696849e-01,  1.32733437e-01, -1.54891530e-01, -1.88269018e-01,
       -1.79980007e-01, -1.54783231e-01,  1.77714914e-01, -6.40949660e-02,
        2.53398390e-01,  5.30334362e-02, -2.45716168e-01,  1.02266999e-02,
       -3.11027291e-02,  

In [15]:
for headline in headline_list:
    company = headline[0]
    year = headline[1]
    month = headline[2]
    page = headline[3]
    vector = headline[5]
    
    filename = company + '_' + year + '_' + month + '_' + page
    np.savetxt('csv/' + filename + '.csv', vector, delimiter=',')